Feature base controller
ui5-community/generator-ui5-ts-app pull request #10
Opened 2022-02-11 14:51 UTC by AlexanderK22

I've added the BaseController.ts. The App.controller.ts and the Main.controller.ts were also changed to extend from it.

2022-02-13 07:34 UTC, vobu requested changes
only small changes in jsdoc, otherwise good to go!

2022-02-13 07:34 UTC, vobu commented on generators/app/templates/src/controller/BaseController.ts
> +	 * @param {string} sName? the model name
please don‘t type the input params in jsdoc - you casted them already in the code, let TS take care of the rest :)
applies to the other jsdoc blocks as well

2022-02-13 07:34 UTC, vobu commented on generators/app/templates/src/controller/BaseController.ts
> +	 * @param {string} sName? the model name
optional params should be denoted like [sName]

2022-02-13 16:51 UTC, AlexanderK22 commented
I've updated the JSDoc in the BaseController.js

2022-02-16 15:20 UTC, petermuessig reviewed
Sorry, for being late to the party. I like your suggestion and have just two minor comments on that - but we can even submit it without changing.

2022-02-16 15:20 UTC, petermuessig commented on generators/app/templates/src/controller/Main.controller.ts
> +import BaseController from "<%= appURI %>/controller/BaseController";
Same here, relative URL should be sufficient.

2022-02-17 08:25 UTC, AlexanderK22 commented
@petermuessig Using a relative URL is probably the better option. I've updated it in the App and Main controller. Thanks for the suggestion 👍.

2022-02-17 09:27 UTC, petermuessig requested changes
Hi @AlexanderK22 ,

sorry to bother you a bit more. I created the application now and run the eslint checks `yarn lint` and the following issues appear:

![image](https://user-images.githubusercontent.com/1589419/154445569-3c43521e-6144-4d9d-977f-ca6fe1ba1798.png)

Would you be able to catch them? Or should I try to assist here? 

I think, in future, we need to add to run the lint on the generated application to validate the content upfront - overall to introduce some tests.

THX and BR,
Peter

2022-02-17 09:37 UTC, AlexanderK22 commented
Hi @petermuessig,
I'd appreciate your assitance in this matter, to resolve the issue as quickly as possible.

Thanks in advance.

2022-02-17 09:38 UTC, petermuessig commented
@AlexanderK22 - ok, I'll try to reserve some time today evening or tomorrow morning to fully sort this out. Big thanks to your contribution so far... 👍

2022-02-17 09:43 UTC, AlexanderK22 commented
@petermuessig thanks again. Glad I could help out a bit.

2022-02-17 16:21 UTC, petermuessig commented
@AlexanderK22 @vobu - codebase is cleaned-up now and should be good to go. The eslint checks are now reporting no issue anymore. 😄

2022-02-18 16:09 UTC, merged

2022-02-18 16:09 UTC, petermuessig commented
@AlexanderK22 - thanks for your contribution. It's merged now, feel free to test it and provide feedback... 😄

2022-02-18 16:12 UTC, AlexanderK22 commented
@petermuessig Great! I will test it and let you know if there are any issues.